apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-helm-chart.fullName" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crud-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crud-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: crud-helm
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: web
              containerPort: 80