apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-helm-chart.fullName" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crud-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crud-helm-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: web
              containerPort: 80
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: crud-secret
                  key: DATABASE_URI
            - name: GREETING
              valueFrom:
                configMapRef:
                  name: crud-config
                  key: GREETING