apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-helm-chart.fullName" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "crud-helm-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
