apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-helm-chart.fullName" . }}
  labels:
    {{- include "crud-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web