apiVersion: batch/v1
kind: Job
metadata:
  name: crud-helm-chart # has been generated wrong name
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: crud-helm-chart # has been generated wrong name
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: "postgresql://myuser:passwd@crud-helm-chart-postgresql" # has been generated wrong wrong host
            - name: POSTGRES_PORT
              value: "5432"
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT;
              do echo waiting for database; sleep 5; done;
      containers:
        - name: post-install-job
          env:
            - name: DATABASE_URI
              value: "postgresql://myuser:passwd@crud-helm-chart-postgresql:5432/myapp"
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              psql $DATABASE_URI <<'EOF'
                CREATE TABLE client (id bigserial primary key, userName varchar, firstName varchar, lastName varchar, email varchar, phone email);
                INSERT INTO client (username, firstName, lastName, email, phone) VALUES ('sabsab', 'Sabina', 'Dubina', 'sabsab@sab.io', '666');
              EOF
  backoffLimit: 0