replicaCount: 2

image:
  repository: dubinkincorp/k8s

service:
  type: NodePort
  port: 8000

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"